### ISSUE TITLE
CropBounds property seems to be readonly after initialization

### ISSUE THREAD

**Issue by HadrienPierart** [AllanBishop/angular-img-cropper#11] opened 2015-05-27 10:27 UTC
Can we use this property to change the bounds dynamically from the parent controller for instance ?
I just tried but it doesnt seem to change anything. I'm trying to set a min width and height on crop size through using cropBounds size as watch.

Here is my code : 
    
    $scope.$watch('pictureUploader.cropBounds', cropBounds => {
    if (cropBounds && cropBounds.top !== undefined) {
      console.log('cropBounds', cropBounds, cropBounds.getWidth(), cropBounds.getHeight());
      if(cropBounds.getWidth() < minCropSize){
        // This is logged properly, yet updating cropBounds has no effect
        console.log('Blocking crop bounds');
        vm.cropBounds.right = cropBounds.left + minCropSize;
        vm.cropBounds.bottom = cropBounds.top + minCropSize;
      }
    }
    });

**Comment by AllanBishop** [comment] 2015-05-27 12:33
getBounds (and therefore getCropBounds) return a new bounds object with values set by calculating the marker positions on the fly. As such it behaves in a read only manner. I will make a function called setBounds which will then update the marker positions which you can then use in your code.

**Comment by AllanBishop** [comment] 2015-05-27 13:18
Ok so I have now added this new function <code> setBounds(bounds)</code>. Just pass in a bounds object and it will update the current crop rectangle. The bounds value is in screen/canvas coordinates so 0,0 is the very top left. Also note that if keepAspect is turned on then the bounds should ideally keep the same aspect. The function is very bare bones so does no checking/clamping of values. Let me know how you go as I have tested it minimally.

**Comment by HadrienPierart** [comment] 2015-05-27 13:45
That sounds great but how should I access this internal function for my controller or my template ?

**Comment by AllanBishop** [comment] 2015-05-28 13:36
Ah yes. Having looked over it again, it seems that it will be better if I integrate the min size feature into the corner dragging logic itself rather than having to watch values etc. Half way through implementing it and will finish it off tomorrow.

**Comment by HadrienPierart** [comment] 2015-05-28 17:05
Awesome ! Thanks a lot, I can't wait to test it !

**Comment by AllanBishop** [comment] 2015-05-29 08:20
Have now updated the code so that either a <code>min-width</code> and/or a <code>min-height</code> can be set for enforcing a min size. This turned out to be more difficult than I initially thought as it needed to work with the enforcing of aspectRatios (if enabled).

**Comment by HadrienPierart** [comment] 2015-05-29 09:48
I'll try to test that today or tomorrow and keep you posted

**Comment by HadrienPierart** [comment] 2015-05-31 08:08
Hi again,

This looks promising but I think it doesn't work properly. How do you calculate the sizes regarding the original image ? 
For instance, if I have an image that is 1200x1200, and min-width/height of 600, I should be able to drag the corners between 600 and 1200. But it seems that as the image is shrunk to fit it in the canvas, the mins are not calculated properly.

See the attached JSbin, If you try to upload a 1200x1200 image, for some reason, the cropping square is locked and I can't resize it, even though my mins are 600...

http://jsbin.com/tujuyaxumu/2/edit?html,js,output

**Comment by HadrienPierart** [comment] 2015-05-31 09:29
Also, can I bind to these properties to variables in my scope like that ? 
    
    min-width="{{myCtrlerAs.minCropSize}}" min-height="{{myCtrlerAs.minCropSize}}"

**Comment by AllanBishop** [comment] 2015-06-01 11:28
The problem is that <code>min-width</code> and <code>min-height</code> are in screen dimensions and not source image dimensions. Set the sizes to something smaller than your <code>crop-width</code> and <code>crop-height</code>  and it should work fine. 

The reason min sizes are in screen dimensions is that they relate directly to the crop area dimension parameters, which, are also in screen space. I did this because the source image dimensions will always be changing and therefore a min crop area on screen would look different depending on the size of the image. Of course maybe there is a particular use case where you think it would be better for it to be based on the source image dimensions instead?

Also I have now updated it for two-way binding so you can link to your properties.

**Comment by HadrienPierart** [comment] 2015-06-02 06:26
Hi Allan,

Indeed this info helped me figuring this out. It does work better when you keep the min-* equal or below crop-*. However, I'm having issues with a 1200x1200 image that breaks the clamps position and I can't figure If the issue is in my code or if I found a bug in some corner case. Could you update your jsbin demo with the latest version of the lib so that I can test this scenario ?

Thanks a lot !

**Comment by AllanBishop** [comment] 2015-06-02 10:00
I have updated the JSbin. Let me know what settings you are using with it so I can replicate the issue.

**Comment by HadrienPierart** [comment] 2015-06-04 13:41
Yep, I did fix one of my issues, but now I've noticed that when you swap pictures, the canvas does not seem to reset properly and keeps some of the config of the previous image.
For instance, on this JSBin :
http://jsbin.com/gupopomofa/1/edit?html,js,output

If I put in a 928x580 image with the config, the crop bounds are set on the boundaries of the image in the canvas as expected, but If I start after a refresh with a 540x800 image then swap it for the 928x580, then the crop bounds remain like they on the previous image ...

**Comment by AllanBishop** [comment] 2015-06-05 07:32
Ah yes. I have now fixed this. The crop area will now default to the max possible size with respect to any of the parameters such as crop ratio. This seems to fix the scenario you mentioned.

**Comment by HadrienPierart** [comment] 2015-06-05 07:34
Thanks !
I'll try to give it a try this afternoon or in the week-end.

**Comment by HadrienPierart** [comment] 2015-06-05 14:39
Excellent, everything works perfectly now !
I still need to try a lot on mobile so maybe i'll come back with new issues in a few days ;)

Keep up the good work !

**Comment by AllanBishop** [comment] 2015-06-06 02:05
Great! Had a quick test running it on an IPad3. It seems to be working well although performance seems to have dropped a little so I might have to investigate that.

**Closed by AllanBishop** 2015-06-06 02:05 UTC
